# air.toml

root = "."
tmp_dir = "tmp"
build_args = ["-tags", "development"]

[build]
  binary = "./main"
  exclude_dir = ["assets", "tmp"]
  exclude_file = ["main.go"]

[log]
  error_log = "logs/error.log"
  warn_log = "logs/warn.log"
  info_log = "logs/info.log"
  debug_log = "logs/debug.log"
